import { Dictionary, Language } from './types';

const en: Dictionary = {
  toasts: {
    loginSuccessTitle: 'Welcome back!', loginSuccessDesc: 'You have successfully signed in.', otpSentTitle: 'Code Sent', otpSentDesc: 'Please check your email for the verification code.', otpVerifiedTitle: 'Verified', otpVerifiedDesc: 'Your code has been verified successfully.',
    logoutSuccessTitle: 'Signed Out', logoutSuccessDesc: 'You have been successfully signed out.', signupSuccessTitle: 'Account Created', signupSuccessDesc: 'Please check your email to verify your account.', networkErrorTitle: 'Network Error', networkErrorDesc: 'Please check your internet connection and try again.', validationErrorTitle: 'Validation Error', validationErrorDesc: 'Almost there! Please check the highlighted fields.', missingFieldsTitle: 'Missing Fields', missingFieldsDesc: 'This field is important. Please don\'t leave it blank.', saveSuccessTitle: 'Saved!', saveSuccessDesc: 'Changes have been saved successfully.', deleteSuccessTitle: 'Deleted!', deleteSuccessDesc: 'Record has been deleted successfully.', loadingTitle: 'Loading...', loadingDesc: 'Just a moment, we\'re getting things ready...', noResultsTitle: 'No Results', noResultsDesc: 'We couldn\'t find anything here. Let\'s try again?', accessDeniedTitle: 'Access Denied', accessDeniedDesc: 'Oops! You don\'t have permission to enter here.', errorTitle: 'Error!', errorDesc: 'An unexpected error occurred. Please try again.', aiSuccessTitle: 'Success!', aiSuccessDesc: 'AI processed your input correctly.', aiErrorTitle: 'Error!', aiErrorDesc: 'There was an error processing your input.', queryAddedTitle: 'Success!', queryAddedDesc: 'Your query has been added.', queryResolvedTitle: 'Success!', queryResolvedDesc: 'Query has been resolved.', timerStartedTitle: 'Success!', timerStartedDesc: 'Timer has been started.', statusUpdatedTitle: 'Saved!', statusUpdatedDesc: 'Status has been updated.', notificationsClearedTitle: 'Success!', notificationsClearedDesc: 'All notifications cleared.', assignmentsSuccessTitle: 'Success!', assignmentsSuccessDesc: 'Assignments updated successfully.',
  },
  common: { loading: 'Loading...', save: 'Save', cancel: 'Cancel', delete: 'Delete', edit: 'Edit', close: 'Close', success: 'Success', error: 'Error', yes: 'Yes', no: 'No', confirm: 'Confirm', refresh: 'Refresh', email: 'Email', or: 'OR', created: 'Created: ', published: 'Published', start_date: 'Start Date: ', },
  navigation: { dashboard: 'Dashboard', log: 'Log Time', history: 'History', reports: 'Reports', team: 'Team', settings: 'Settings', signOut: 'Sign Out', newEntry: 'New Entry', },
  auth: { signIn: 'Sign In', signUp: 'Sign Up', createAccount: 'Create an account', haveAccount: 'Already have an account? Sign In', noAccount: "Don't have an account? Sign Up", firstName: 'First Name', lastName: 'Last Name', roleTitle: 'Role', termsPrefix: 'By signing in, you agree to our ', termsLink: 'Terms of Service', termsAnd: ' and ', privacyLink: 'Privacy Policy', signOut: 'Sign Out', sendOtp: 'Send Code', verifyOtp: 'Verify', otpCode: 'Code', useOtp: 'Use Code (OTP)', usePassword: 'Use Password', checkEmailForOtp: 'Check your email for the OTP code.', otpPlaceholder: '123456', email: 'Email', password: 'Password', accessDenied: 'Access Denied', pendingApproval: 'Pending Approval', contactAdmin: 'Please contact your administrator.', accountRejected: 'Your account access has been rejected.', selectRole: 'Select a role' },
  roles: { super_admin: 'Super Admin', manager: 'Manager', crc: 'CRC', cra: 'CRA', data_entry: 'Data Entry', recruitment_specialist: 'Recruitment Specialist', retention_specialist: 'Retention Specialist', cta: 'CTA', ra: 'RA', staff: 'Staff' },
  status: { active: 'Active', pending: 'Pending', rejected: 'Rejected', published: 'Published' },
  dashboard: { overview: 'Overview of activities.', todayLogs: 'Today', thisWeekLogs: 'This Week', openQueries: 'Open Queries', actions: 'Actions', logNewActivity: 'Log New Activity', viewHistory: 'View History', noDataThisWeek: 'No data for this week yet.', quickLog: 'QUICK LOG', repeatRecent: 'Repeat Recent', activityDistribution: 'Activity Distribution', recentEntries: 'Recent Entries', viewAll: 'View All', noRecentEntries: 'No recent entries.', time: 'Time', entries: 'Entries', teamManagement: 'Team Management', reviewTeamHistory: 'Review Team History', productivityDiagnosis: 'Productivity Diagnosis', keepWorkingOn: 'Keep working on...' },
  shell: { appName: 'SiteFlow', appSubtitle: 'Clinical Ops Time Tracker', smartTimer: 'Smart Timer', stopLog: 'Stop & Log', notifications: 'Notifications', markAllRead: 'Mark all as read', clearAll: 'Clear all', noNotifications: 'No new notifications' },
  logForm: { title: 'Log Time', subtitle: 'Log activities as', aiSmartLogging: 'AI Smart Logging', aiDescription: 'Describe what you did naturally, and our AI will fill out the form for you.', aiPlaceholder: 'e.g., Spent 2 hours reviewing ICFs for Protocol A at Site 101...', aiButton: 'Auto-fill', date: 'Date', duration: 'Duration', project: 'Project', protocol: 'Protocol', siteOptional: 'Site (Optional)', category: 'Category', task: 'Task', notesOptional: 'Notes (Optional)', notesPlaceholder: 'Add any additional context or details...', submit: 'Save Log', selectProject: 'Select Project...', selectProtocol: 'Select Protocol...', selectSite: 'Select Site...', hours: 'h', minutes: 'm', aiSuccess: 'AI filled the form successfully.', aiError: 'Failed to process text. Please fill manually.', aiInputTooLong: 'Text is too long (max 2000 chars).', specificActivity: 'Specific Activity', siteLed: 'Site Led', croLed: 'CRO Led', shared: 'Shared', selectSubTask: 'Select Sub-Task', subTasks: 'sub-tasks', noCategoriesAvailable: 'No categories available' },
  history: { title: 'History & Queries', subtitle: 'Review logs and answer data queries.', searchPlaceholder: 'Search by category or activity...', allProjects: 'All Projects', allProtocols: 'All Protocols', date: 'Date', duration: 'Duration', project: 'Project', category: 'Category', activity: 'Activity', noLogs: 'No logs found matching current filters.', openQuery: 'Open Query', askQuestion: 'Ask Question', question: 'Question', reply: 'Reply', yourReply: 'Your Reply', sendReply: 'Send Reply' },
  reports: { title: 'Reports & Analytics', subtitle: 'View time distribution and statistics.', timeByProject: 'Time by Project', timeByCategory: 'Time by Category', noData: 'No data available to display reports.', export: 'Export CSV', generateInsights: 'Generate AI Insights', aiWeeklyInsights: 'AI Weekly Insights', timesheetReport: 'Timesheet Report', page: 'Page', resource: 'Resource', periodName: 'Period Name', date: 'Date', projectNum: 'Project No.', projectDesc: 'Project Description', taskNum: 'Task No.', taskDesc: 'Task Description', details: 'Details', status: 'Status', regularAmount: 'Regular Amount', total: 'TOTAL', allActivities: 'All Activities', filters: 'Filters', description: 'Description', aiInsightsSummary: 'AI Insights & Activity Summary' },
  team: { title: 'Team Management', subtitle: 'Manage team access and assignments.', users: 'Users', projects: 'Projects', protocols: 'Protocols', name: 'Name', role: 'Role', status: 'Status', actions: 'Actions', approve: 'Approve', reject: 'Reject', teamMembers: 'Team Members', noTeamMembers: 'No team members found', ifStaffAssigned: 'If you have staff assigned, they will appear here.', refreshTeamData: 'Refresh Team Data', profileSuffix: ' - Profile', saveAssignments: 'Save Assignments', assignmentsSuccess: 'Assignments updated successfully', projectProtocolAssignments: 'Project & Protocol Assignments', selectProtocolsFor: 'Select Protocols for' },
  settings: { title: 'System Settings', subtitle: 'Manage categories, activities, and preferences.', activitiesAndRoles: 'Activities & Roles', generalSettings: 'General Settings', activityCategories: 'Activity Categories', newCategory: 'New Category', addRole: 'Add Role', addSubTask: 'Add Sub-task', newTask: 'New Task', noCategories: 'No categories configured. Create one or run the database seed.', underConstruction: 'Under Construction', generalSettingsDesc: 'General settings are under development. Check back soon for new configuration options.' },
  legal: { termsTitle: 'Terms of Service', privacyTitle: 'Privacy Policy', termsContent: 'Welcome to SiteFlow. By accessing our platform, you agree to these terms...', privacyContent: 'Your privacy is important to us...' }
};

const es: Dictionary = {
  toasts: {
    loginSuccessTitle: '¡Bienvenido de nuevo!', loginSuccessDesc: 'Has iniciado sesión correctamente.', otpSentTitle: 'Código Enviado', otpSentDesc: 'Por favor, revisa tu correo electrónico para ver el código de verificación.', otpVerifiedTitle: 'Verificado', otpVerifiedDesc: 'Tu código ha sido verificado correctamente.', logoutSuccessTitle: 'Sesión Cerrada', logoutSuccessDesc: 'Has cerrado sesión correctamente.', signupSuccessTitle: 'Cuenta Creada', signupSuccessDesc: 'Por favor, revisa tu correo electrónico para verificar tu cuenta.', networkErrorTitle: 'Error de Red', networkErrorDesc: 'Por favor, comprueba tu conexión a internet e inténtalo de nuevo.', validationErrorTitle: 'Error de Validación', validationErrorDesc: '¡Casi listo! Por favor, revisa los campos marcados.', missingFieldsTitle: 'Campos Incompletos', missingFieldsDesc: 'Este campo es importante. No lo dejes en blanco.', saveSuccessTitle: '¡Guardado!', saveSuccessDesc: 'Los cambios se han guardado correctamente.', deleteSuccessTitle: '¡Eliminado!', deleteSuccessDesc: 'El registro se ha eliminado correctamente.', loadingTitle: 'Cargando...', loadingDesc: 'Solo un momento, estamos preparando todo...', noResultsTitle: 'Sin Resultados', noResultsDesc: 'No pudimos encontrar nada aquí. ¿Intentamos de nuevo?', accessDeniedTitle: 'Acceso Denegado', accessDeniedDesc: '¡Ups! No tienes permiso para entrar aquí.', errorTitle: '¡Error!', errorDesc: 'Ocurrió un error inesperado. Por favor, inténtalo de nuevo.', aiSuccessTitle: '¡Éxito!', aiSuccessDesc: 'La IA procesó tu entrada correctamente.', aiErrorTitle: '¡Error!', aiErrorDesc: 'Hubo un error al procesar tu entrada.', queryAddedTitle: '¡Éxito!', queryAddedDesc: 'Tu consulta ha sido añadida.', queryResolvedTitle: '¡Éxito!', queryResolvedDesc: 'La consulta ha sido resuelta.', timerStartedTitle: '¡Éxito!', timerStartedDesc: 'El temporizador ha comenzado.', statusUpdatedTitle: '¡Guardado!', statusUpdatedDesc: 'El estado ha sido actualizado.', notificationsClearedTitle: '¡Éxito!', notificationsClearedDesc: 'Todas las notificaciones fueron borradas.', assignmentsSuccessTitle: '¡Éxito!', assignmentsSuccessDesc: 'Asignaciones actualizadas correctamente.',
  },
  common: { loading: 'Cargando...', save: 'Guardar', cancel: 'Cancelar', delete: 'Eliminar', edit: 'Editar', close: 'Cerrar', success: 'Éxito', error: 'Error', yes: 'Sí', no: 'No', confirm: 'Confirmar', refresh: 'Actualizar', email: 'Correo', or: 'O', created: 'Creado: ', published: 'Publicado', start_date: 'Fecha de inicio: ', },
  navigation: { dashboard: 'Panel', log: 'Registrar Tiempo', history: 'Historial', reports: 'Reportes', team: 'Equipo', settings: 'Configuración', signOut: 'Cerrar Sesión', newEntry: 'Nueva Entrada', },
  auth: { signIn: 'Iniciar Sesión', signUp: 'Registrarse', createAccount: 'Crear una cuenta', haveAccount: '¿Ya tienes una cuenta? Iniciar Sesión', noAccount: '¿No tienes una cuenta? Registrarse', firstName: 'Nombre', lastName: 'Apellido', roleTitle: 'Rol', termsPrefix: 'Al iniciar sesión, aceptas nuestros ', termsLink: 'Términos de Servicio', termsAnd: ' y la ', privacyLink: 'Política de Privacidad', signOut: 'Cerrar Sesión', sendOtp: 'Enviar Código', verifyOtp: 'Verificar', otpCode: 'Código', useOtp: 'Usar Código (OTP)', usePassword: 'Usar Contraseña', checkEmailForOtp: 'Revisa tu correo para ver el código OTP.', otpPlaceholder: '123456', email: 'Correo', password: 'Contraseña', accessDenied: 'Acceso Denegado', pendingApproval: 'Aprobación Pendiente', contactAdmin: 'Por favor, contacta a tu administrador.', accountRejected: 'El acceso a tu cuenta ha sido rechazado.', selectRole: 'Seleccione un rol' },
  roles: { super_admin: 'Super Admin', manager: 'Gerente', crc: 'CRC', cra: 'CRA', data_entry: 'Entrada de Datos', recruitment_specialist: 'Especialista en Reclutamiento', retention_specialist: 'Especialista en Retención', cta: 'CTA', ra: 'RA', staff: 'Staff' },
  status: { active: 'Activo', pending: 'Pendiente', rejected: 'Rechazado', published: 'Publicado' },
  dashboard: { overview: 'Resumen de actividades.', todayLogs: 'Hoy', thisWeekLogs: 'Esta Semana', openQueries: 'Consultas Abiertas', actions: 'Acciones', logNewActivity: 'Registrar Nueva Actividad', viewHistory: 'Ver Historial', noDataThisWeek: 'Aún no hay datos para esta semana.', quickLog: 'REGISTRO RÁPIDO', repeatRecent: 'Repetir Reciente', activityDistribution: 'Distribución de Actividad', recentEntries: 'Entradas Recientes', viewAll: 'Ver Todo', noRecentEntries: 'No hay entradas recientes.', time: 'Tiempo', entries: 'Entradas', teamManagement: 'Gestión de Equipo', reviewTeamHistory: 'Revisar Historial del Equipo', productivityDiagnosis: 'Diagnóstico de Productividad', keepWorkingOn: 'Continuar trabajando en...' },
  shell: { appName: 'SiteFlow', appSubtitle: 'Registro de Operaciones Clínicas', smartTimer: 'Temporizador Inteligente', stopLog: 'Parar y Registrar', notifications: 'Notificaciones', markAllRead: 'Marcar todas como leídas', clearAll: 'Limpiar todas', noNotifications: 'No hay notificaciones nuevas' },
  logForm: { title: 'Registrar Tiempo', subtitle: 'Registrar actividades como', aiSmartLogging: 'Registro Inteligente IA', aiDescription: 'Describe lo que hiciste de forma natural, y nuestra IA llenará el formulario por ti.', aiPlaceholder: 'ej., Pasé 2 horas revisando ICFs para el Protocolo A en el Sitio 101...', aiButton: 'Autocompletar', date: 'Fecha', duration: 'Duración', project: 'Proyecto', protocol: 'Protocolo', siteOptional: 'Sitio (Opcional)', category: 'Categoría', task: 'Tarea', notesOptional: 'Notas (Opcional)', notesPlaceholder: 'Agrega cualquier contexto o detalle adicional...', submit: 'Guardar Registro', selectProject: 'Seleccionar Proyecto...', selectProtocol: 'Seleccionar Protocolo...', selectSite: 'Seleccionar Sitio...', hours: 'h', minutes: 'm', aiSuccess: 'La IA completó el formulario con éxito.', aiError: 'Error al procesar el texto. Por favor, llena manualmente.', aiInputTooLong: 'El texto es muy largo (máximo 2000 caracteres).', specificActivity: 'Actividad Específica', siteLed: 'Local', croLed: 'CRO', shared: 'Compartido', selectSubTask: 'Seleccionar Sub-tarea', subTasks: 'sub-tareas', noCategoriesAvailable: 'No hay categorías disponibles' },
  history: { title: 'Historial y Consultas', subtitle: 'Revisar registros y responder consultas de datos.', searchPlaceholder: 'Buscar por categoría o actividad...', allProjects: 'Todos los Proyectos', allProtocols: 'Todos los Protocolos', date: 'Fecha', duration: 'Duración', project: 'Proyecto', category: 'Categoría', activity: 'Actividad', noLogs: 'No se encontraron registros con los filtros actuales.', openQuery: 'Abrir Consulta', askQuestion: 'Hacer Pregunta', question: 'Pregunta', reply: 'Responder', yourReply: 'Tu Respuesta', sendReply: 'Enviar Respuesta' },
  reports: { title: 'Reportes y Análisis', subtitle: 'Ver distribución de tiempo y estadísticas.', timeByProject: 'Tiempo por Proyecto', timeByCategory: 'Tiempo por Categoría', noData: 'No hay datos disponibles para mostrar reportes.', export: 'Exportar CSV', generateInsights: 'Generar Insights con IA', aiWeeklyInsights: 'Insights Semanales de IA', timesheetReport: 'Informe de hoja de horas', page: 'Página', resource: 'Recurso', periodName: 'Nombre periodo', date: 'Fecha', projectNum: 'Nº Proyecto', projectDesc: 'Descripción proyecto', taskNum: 'Nº de Tarea', taskDesc: 'Descripción de la tarea', details: 'Detalles', status: 'Estado', regularAmount: 'Cantidad regular', total: 'TOTAL', allActivities: 'Todas las actividades', filters: 'Filtros', description: 'Descripción', aiInsightsSummary: 'Resumen de Actividades e Insights de IA' },
  team: { title: 'Gestión de Equipo', subtitle: 'Gestionar accesos y asignaciones del equipo.', users: 'Usuarios', projects: 'Proyectos', protocols: 'Protocolos', name: 'Nombre', role: 'Rol', status: 'Estado', actions: 'Acciones', approve: 'Aprobar', reject: 'Rechazar', teamMembers: 'Miembros del Equipo', noTeamMembers: 'No se encontraron miembros del equipo', ifStaffAssigned: 'Si tienes personal asignado, aparecerán aquí.', refreshTeamData: 'Actualizar Datos del Equipo', profileSuffix: ' - Perfil', saveAssignments: 'Guardar Asignaciones', assignmentsSuccess: 'Asignaciones actualizadas correctamente', projectProtocolAssignments: 'Asignaciones de Proyecto y Protocolo', selectProtocolsFor: 'Seleccionar Protocolos para' },
  settings: { title: 'Configuración del Sistema', subtitle: 'Administra categorías, actividades y preferencias.', activitiesAndRoles: 'Actividades y Roles', generalSettings: 'Configuración General', activityCategories: 'Categorías de Actividades', newCategory: 'Nueva Categoría', addRole: 'Agregar Rol', addSubTask: 'Agregar Sub-tarea', newTask: 'Nueva Tarea', noCategories: 'No hay categorías configuradas. Crea una o ejecuta el seed de la base de datos.', underConstruction: 'En Construcción', generalSettingsDesc: 'Las configuraciones generales están en desarrollo. Vuelve pronto para nuevas opciones de configuración.' },
  legal: { termsTitle: 'Términos de Servicio', privacyTitle: 'Política de Privacidad', termsContent: 'Bienvenido a SiteFlow. Al acceder a nuestra plataforma, aceptas estos términos...', privacyContent: 'Tu privacidad es importante para nosotros...' }
};

const pt: Dictionary = {
  toasts: {
    loginSuccessTitle: 'Bem-vindo de volta!', loginSuccessDesc: 'Você entrou com sucesso.', otpSentTitle: 'Código Enviado', otpSentDesc: 'Por favor, verifique seu e-mail para o código de verificação.', otpVerifiedTitle: 'Verificado', otpVerifiedDesc: 'Seu código foi verificado com sucesso.', logoutSuccessTitle: 'Desconectado', logoutSuccessDesc: 'Você foi desconectado com sucesso.', signupSuccessTitle: 'Conta Criada', signupSuccessDesc: 'Por favor, verifique seu e-mail para validar sua conta.', networkErrorTitle: 'Erro de Rede', networkErrorDesc: 'Por favor, verifique sua conexão com a internet e tente novamente.', validationErrorTitle: 'Erro de Validação', validationErrorDesc: 'Quase lá! Por favor, verifique os campos marcados.', missingFieldsTitle: 'Campos Incompletos', missingFieldsDesc: 'Este campo é importante. Não o deixe em branco.', saveSuccessTitle: 'Salvo!', saveSuccessDesc: 'As alterações foram salvas com sucesso.', deleteSuccessTitle: 'Excluído!', deleteSuccessDesc: 'O registro foi excluído com sucesso.', loadingTitle: 'Carregando...', loadingDesc: 'Só um momento, estamos preparando as coisas...', noResultsTitle: 'Sem Resultados', noResultsDesc: 'Não conseguimos encontrar nada aqui. Vamos tentar de novo?', accessDeniedTitle: 'Acesso Negado', accessDeniedDesc: 'Ops! Você não tem permissão para entrar aqui.', errorTitle: 'Erro!', errorDesc: 'Ocorreu um erro inesperado. Por favor, tente novamente.', aiSuccessTitle: 'Sucesso!', aiSuccessDesc: 'A IA processou sua entrada corretamente.', aiErrorTitle: 'Erro!', aiErrorDesc: 'Houve um erro ao processar sua entrada.', queryAddedTitle: 'Sucesso!', queryAddedDesc: 'Sua consulta foi adicionada.', queryResolvedTitle: 'Sucesso!', queryResolvedDesc: 'A consulta foi resolvida.', timerStartedTitle: 'Sucesso!', timerStartedDesc: 'O temporizador foi iniciado.', statusUpdatedTitle: 'Salvo!', statusUpdatedDesc: 'O status foi atualizado.', notificationsClearedTitle: 'Sucesso!', notificationsClearedDesc: 'Todas as notificações foram apagadas.', assignmentsSuccessTitle: 'Sucesso!', assignmentsSuccessDesc: 'Atribuições atualizadas com sucesso.',
  },
  common: { loading: 'Carregando...', save: 'Salvar', cancel: 'Cancelar', delete: 'Excluir', edit: 'Editar', close: 'Fechar', success: 'Sucesso', error: 'Erro', yes: 'Sim', no: 'Não', confirm: 'Confirmar', refresh: 'Atualizar', email: 'E-mail', or: 'OU', created: 'Criado: ', published: 'Publicado', start_date: 'Data de início: ', },
  navigation: { dashboard: 'Painel', log: 'Registrar Tempo', history: 'Histórico', reports: 'Relatórios', team: 'Equipe', settings: 'Configurações', signOut: 'Sair', newEntry: 'Nova Entrada', },
  auth: { signIn: 'Entrar', signUp: 'Inscrever-se', createAccount: 'Criar Conta', haveAccount: 'Já tem uma conta? Entrar', noAccount: 'Não tem uma conta? Inscrever-se', firstName: 'Nome', lastName: 'Sobrenome', roleTitle: 'Função', termsPrefix: 'Ao entrar, você concorda com os ', termsLink: 'Termos de Serviço', termsAnd: ' e a ', privacyLink: 'Política de Privacidade', signOut: 'Sair', sendOtp: 'Enviar Código', verifyOtp: 'Verificar', otpCode: 'Código', useOtp: 'Usar Código (OTP)', usePassword: 'Usar Senha', checkEmailForOtp: 'Verifique seu e-mail para ver o código OTP.', otpPlaceholder: '123456', email: 'E-mail', password: 'Senha', accessDenied: 'Acesso Negado', pendingApproval: 'Aprovação Pendente', contactAdmin: 'Por favor, contate o seu administrador.', accountRejected: 'Sua solicitação de conta foi rejeitada. Por favor contate o administrador.', selectRole: 'Selecione um cargo' },
  roles: { super_admin: 'Super Administrador', manager: 'Gerente', crc: 'CRC', cra: 'CRA', data_entry: 'Data Entry', recruitment_specialist: 'Especialista em Recrutamento', retention_specialist: 'Especialista em Retenção', cta: 'CTA', ra: 'RA', staff: 'Staff' },
  status: { active: 'Ativo', pending: 'Pendente', rejected: 'Rejeitado', published: 'Publicado' },
  dashboard: { overview: 'Visão geral das atividades.', todayLogs: 'Hoje', thisWeekLogs: 'Esta Semana', openQueries: 'Consultas Abertas', actions: 'Ações', logNewActivity: 'Registrar Nova Atividade', viewHistory: 'Ver Histórico', noDataThisWeek: 'Não há dados para esta semana ainda.', quickLog: 'REGISTRO RÁPIDO', repeatRecent: 'Repetir Reciente', activityDistribution: 'Distribuição de Atividade', recentEntries: 'Entradas Recientes', viewAll: 'Ver Tudo', noRecentEntries: 'Nenhuma entrada recente.', time: 'Tempo', entries: 'Entradas', teamManagement: 'Gestão de Equipe', reviewTeamHistory: 'Revisar Histórico da Equipe', productivityDiagnosis: 'Diagnóstico de Produtividade', keepWorkingOn: 'Continuar trabalhando em...' },
  shell: { appName: 'SiteFlow', appSubtitle: 'Registro de Operações Clínicas', smartTimer: 'Timer Inteligente', stopLog: 'Parar e Registrar', notifications: 'Notificações', markAllRead: 'Marcar todas como lidas', clearAll: 'Limpar todas', noNotifications: 'Nenhuma notificação nova' },
  logForm: { title: 'Registrar Tempo', subtitle: 'Registrar atividades como', aiSmartLogging: 'Registro Inteligente IA', aiDescription: 'Descreva o que você fez naturalmente, e nossa IA preencherá o formulário para você.', aiPlaceholder: 'ex., Passei 2 horas revisando Termos de Consentimento para o Protocolo A no Local 101...', aiButton: 'Preenchimento Automático', date: 'Data', duration: 'Duração', project: 'Projeto', protocol: 'Protocolo', siteOptional: 'Local (Opcional)', category: 'Categoria', task: 'Tarefa', notesOptional: 'Notas (Opcional)', notesPlaceholder: 'Adicione qualquer contexto ou detalhe adicional...', submit: 'Salvar Registro', selectProject: 'Selecionar Projeto...', selectProtocol: 'Selecionar Protocolo...', selectSite: 'Selecionar Local...', hours: 'h', minutes: 'm', aiSuccess: 'A IA preencheu o formulário com sucesso.', aiError: 'Falha ao processar o texto. Por favor, preencha manualmente.', aiInputTooLong: 'O texto é muito longo (máximo de 2000 caracteres).', specificActivity: 'Atividade Específica', siteLed: 'Local', croLed: 'CRO', shared: 'Compartilhado', selectSubTask: 'Selecionar Sub-Tarefa', subTasks: 'sub-tarefas', noCategoriesAvailable: 'Nenhuma categoria disponível' },
  history: { title: 'Histórico e Consultas', subtitle: 'Revise registros e responda a consultas de dados.', searchPlaceholder: 'Buscar por categoria ou atividade...', allProjects: 'Todos Projetos', allProtocols: 'Todos Protocolos', date: 'Data', duration: 'Duração', project: 'Projeto', category: 'Categoria', activity: 'Atividade', noLogs: 'Nenhum registro encontrado com os filtros atuais.', openQuery: 'Abrir Consulta', askQuestion: 'Fazer Pergunta', question: 'Pergunta', reply: 'Responder', yourReply: 'Sua Resposta', sendReply: 'Enviar Resposta' },
  reports: { title: 'Relatórios e Análises', subtitle: 'Visualize a distribuição de tempo e estatísticas.', timeByProject: 'Tempo por Projeto', timeByCategory: 'Tempo por Categoria', noData: 'Nenhum dado disponível para exibir relatórios.', export: 'Exportar CSV', generateInsights: 'Gerar Insights com IA', aiWeeklyInsights: 'Insights Semanais de IA', timesheetReport: 'Relatório de quadro de horários', page: 'Página', resource: 'Recurso', periodName: 'Nome do período', date: 'Data', projectNum: 'Nº Projeto', projectDesc: 'Descrição do projeto', taskNum: 'Nº Tarefa', taskDesc: 'Descrição da tarefa', details: 'Detalhes', status: 'Status', regularAmount: 'Quantidade regular', total: 'TOTAL', allActivities: 'Todas as Atividades', filters: 'Filtros', description: 'Descrição', aiInsightsSummary: 'Resumo de Atividades e Insights de IA' },
  team: { title: 'Gestão de Equipe', subtitle: 'Gerencie acessos e atribuições da equipe.', users: 'Usuários', projects: 'Projetos', protocols: 'Protocolos', name: 'Nome', role: 'Função', status: 'Status', actions: 'Ações', approve: 'Aprobar', reject: 'Rejeitar', teamMembers: 'Membros da Equipe', noTeamMembers: 'Nenhum membro da equipe encontrado', ifStaffAssigned: 'Se você tiver funcionários atribuídos, eles aparecerão aqui.', refreshTeamData: 'Atualizar Dados da Equipe', profileSuffix: ' - Perfil', saveAssignments: 'Salvar Atribuições', assignmentsSuccess: 'Atribuições atualizadas com sucesso', projectProtocolAssignments: 'Atribuições de Projetos e Protocolos', selectProtocolsFor: 'Selecionar Protocolos para' },
  settings: { title: 'Configurações do Sistema', subtitle: 'Gerencie categorias, atividades e preferências.', activitiesAndRoles: 'Atividades e Funções', generalSettings: 'Configurações Gerais', activityCategories: 'Categorias de Atividades', newCategory: 'Nova Categoria', addRole: 'Adicionar Função', addSubTask: 'Adicionar Sub-tarefa', newTask: 'Nova Tarefa', noCategories: 'Nenhuma categoria configurada. Crie uma ou execute o seed do banco de dados.', underConstruction: 'Em Construção', generalSettingsDesc: 'As configurações gerais estão em desenvolvimento. Volte em breve para novas opções de configuração.' },
  legal: { termsTitle: 'Termos de Serviço', privacyTitle: 'Política de Privacidade', termsContent: 'Bem-vindo ao SiteFlow. Ao acessar nossa plataforma, você concorda com estes termos...', privacyContent: 'Sua privacidade é importante para nós...' }
};

export const dictionaries: Record<Language, Dictionary> = { en, es, pt };
