import { Dictionary, Language } from './types';

export const en: Dictionary = {
  common: { loading: 'Loading...', save: 'Save', cancel: 'Cancel', delete: 'Delete', edit: 'Edit', close: 'Close', success: 'Success', error: 'Error', yes: 'Yes', no: 'No', confirm: 'Confirm', },
  navigation: { dashboard: 'Dashboard', log: 'Log Time', history: 'History', reports: 'Reports', team: 'Team', },
  auth: { signIn: 'Sign In', signUp: 'Sign Up', createAccount: 'Create Account', haveAccount: 'Already have an account? Sign in', noAccount: "Don't have an account? Sign up", firstName: 'First Name', lastName: 'Last Name', roleTitle: 'Role', termsText: "By signing in, you agree to SiteFlow's Terms of Service and Privacy Policy.", signOut: 'Sign Out', email: 'Email', password: 'Password', accessDenied: 'Access Denied', pendingApproval: 'Pending Approval', contactAdmin: 'Please contact your administrator.', },
  roles: { manager: 'Manager', cra: 'CRA', lead: 'Lead', super_admin: 'Super Admin', },
  status: { active: 'Active', pending: 'Pending', rejected: 'Rejected', },
  dashboard: { overview: 'Overview of activities.', todayLogs: 'Today', thisWeekLogs: 'This Week', openQueries: 'Open Queries', actions: 'Actions', logNewActivity: 'Log New Activity', viewHistory: 'View History', quickLog: 'QUICK LOG', repeatRecent: 'Repeat Recent', activityDistribution: 'Activity Distribution', recentEntries: 'Recent Entries', viewAll: 'View All', noRecentEntries: 'No recent entries to show.', time: 'Time', entries: 'Entries', },
  shell: { appName: 'SiteFlow', appSubtitle: 'Clinical Operations Logger', smartTimer: 'Smart Timer', stopLog: 'Stop & Log', notifications: 'Notifications', markAllRead: 'Mark all read', clearAll: 'Clear all', noNotifications: 'No new notifications', },
  logForm: { title: 'Log Time', subtitle: 'Record activities as', aiSmartLogging: 'AI Smart Logging', aiDescription: 'Describe what you did naturally, and our AI will fill out the form for you.', aiPlaceholder: 'e.g., I spent 2 hours reviewing ICFs for Protocol A at Site 101...', aiButton: 'Auto-Fill', date: 'Date', duration: 'Duration', project: 'Project', protocol: 'Protocol', siteOptional: 'Site (Optional)', category: 'Category', specificActivity: 'Specific Activity', task: 'Task', notesOptional: 'Notes (Optional)', notesPlaceholder: 'Add any additional context or details...', submit: 'Save Log Entry', selectProject: 'Select Project...', selectProtocol: 'Select Protocol...', selectSite: 'Select Site...', hours: 'h', minutes: 'm', aiSuccess: 'AI successfully filled the form.', aiError: 'Failed to parse text. Please fill manually.', },
  history: { title: 'History & Queries', subtitle: 'Review logs and respond to data queries.', searchPlaceholder: 'Search by category or activity...', allProjects: 'All Projects', allProtocols: 'All Protocols', date: 'Date', duration: 'Duration', project: 'Project', category: 'Category', activity: 'Activity', noLogs: 'No logs found matching the current filters.', openQuery: 'Open Query', askQuestion: 'Ask Question', question: 'Question', reply: 'Reply', yourReply: 'Your Reply', sendReply: 'Send Reply', },
  reports: { title: 'Reports & Analytics', subtitle: 'View time distribution and insights.', timeByProject: 'Time by Project', timeByCategory: 'Time by Category', noData: 'No data available to display reports.', export: 'Export CSV', },
  team: { title: 'Team Management', subtitle: 'Manage team access and assignments.', users: 'Users', projects: 'Projects', protocols: 'Protocols', name: 'Name', role: 'Role', status: 'Status', actions: 'Actions', approve: 'Approve', reject: 'Reject', },
};

export const es: Dictionary = {
  common: { loading: 'Cargando...', save: 'Guardar', cancel: 'Cancelar', delete: 'Eliminar', edit: 'Editar', close: 'Cerrar', success: 'Éxito', error: 'Error', yes: 'Sí', no: 'No', confirm: 'Confirmar', },
  navigation: { dashboard: 'Panel', log: 'Registrar Tiempo', history: 'Historial', reports: 'Reportes', team: 'Equipo', },
  auth: { signIn: 'Iniciar Sesión', signUp: 'Registrarse', createAccount: 'Crear Cuenta', haveAccount: '¿Ya tienes una cuenta? Iniciar sesión', noAccount: '¿No tienes cuenta? Regístrate', firstName: 'Nombre', lastName: 'Apellido', roleTitle: 'Rol', termsText: 'Al iniciar sesión, aceptas los Términos de Servicio y la Política de Privacidad de SiteFlow.', signOut: 'Cerrar Sesión', email: 'Correo Electrónico', password: 'Contraseña', accessDenied: 'Acceso Denegado', pendingApproval: 'Aprobación Pendiente', contactAdmin: 'Por favor, contacte a su administrador.', },
  roles: { manager: 'Gerente', cra: 'CRA', lead: 'Líder', super_admin: 'Súper Administrador', },
  status: { active: 'Activo', pending: 'Pendiente', rejected: 'Rechazado', },
  dashboard: { overview: 'Resumen de actividades.', todayLogs: 'Hoy', thisWeekLogs: 'Esta Semana', openQueries: 'Consultas Abiertas', actions: 'Acciones', logNewActivity: 'Registrar Nueva Actividad', viewHistory: 'Ver Historial', quickLog: 'REGISTRO RÁPIDO', repeatRecent: 'Repetir Reciente', activityDistribution: 'Distribución de Actividad', recentEntries: 'Entradas Recientes', viewAll: 'Ver Todo', noRecentEntries: 'No hay entradas recientes.', time: 'Tiempo', entries: 'Entradas', },
  shell: { appName: 'SiteFlow', appSubtitle: 'Registro de Operaciones Clínicas', smartTimer: 'Temporizador Inteligente', stopLog: 'Detener y Registrar', notifications: 'Notificaciones', markAllRead: 'Marcar todas leídas', clearAll: 'Borrar todas', noNotifications: 'No hay notificaciones', },
  logForm: { title: 'Registrar Tiempo', subtitle: 'Registrar actividades como', aiSmartLogging: 'Registro Inteligente IA', aiDescription: 'Describe lo que hiciste de forma natural, y nuestra IA completará el formulario por ti.', aiPlaceholder: 'ej., Pasé 2 horas revisando Consentimientos para el Protocolo A en el Sitio 101...', aiButton: 'Auto-Completar', date: 'Fecha', duration: 'Duración', project: 'Proyecto', protocol: 'Protocolo', siteOptional: 'Sitio (Opcional)', category: 'Categoría', specificActivity: 'Actividad Específica', task: 'Tarea', notesOptional: 'Notas (Opcional)', notesPlaceholder: 'Agrega cualquier contexto o detalle adicional...', submit: 'Guardar Registro', selectProject: 'Seleccionar Proyecto...', selectProtocol: 'Seleccionar Protocolo...', selectSite: 'Seleccionar Sitio...', hours: 'h', minutes: 'm', aiSuccess: 'La IA completó el formulario exitosamente.', aiError: 'Error al procesar el texto. Por favor, completa manualmente.', },
  history: { title: 'Historial y Consultas', subtitle: 'Revisa los registros y responde a consultas de datos.', searchPlaceholder: 'Buscar por categoría o actividad...', allProjects: 'Todos los Proyectos', allProtocols: 'Todos los Protocolos', date: 'Fecha', duration: 'Duración', project: 'Proyecto', category: 'Categoría', activity: 'Actividad', noLogs: 'No se encontraron registros con los filtros actuales.', openQuery: 'Abrir Consulta', askQuestion: 'Hacer Pregunta', question: 'Pregunta', reply: 'Responder', yourReply: 'Tu Respuesta', sendReply: 'Enviar Respuesta', },
  reports: { title: 'Reportes y Análisis', subtitle: 'Visualiza la distribución del tiempo y estadísticas.', timeByProject: 'Tiempo por Proyecto', timeByCategory: 'Tiempo por Categoría', noData: 'No hay datos disponibles para mostrar reportes.', export: 'Exportar CSV', },
  team: { title: 'Gestión de Equipo', subtitle: 'Administra el acceso y asignaciones del equipo.', users: 'Usuarios', projects: 'Proyectos', protocols: 'Protocolos', name: 'Nombre', role: 'Rol', status: 'Estado', actions: 'Acciones', approve: 'Aprobar', reject: 'Rechazar', },
};

export const pt: Dictionary = {
  common: { loading: 'Carregando...', save: 'Salvar', cancel: 'Cancelar', delete: 'Excluir', edit: 'Editar', close: 'Fechar', success: 'Sucesso', error: 'Erro', yes: 'Sim', no: 'Não', confirm: 'Confirmar', },
  navigation: { dashboard: 'Painel', log: 'Registrar Tempo', history: 'Histórico', reports: 'Relatórios', team: 'Equipe', },
  auth: { signIn: 'Entrar', signUp: 'Inscrever-se', createAccount: 'Criar Conta', haveAccount: 'Já tem uma conta? Entrar', noAccount: 'Não tem uma conta? Inscrever-se', firstName: 'Nome', lastName: 'Sobrenome', roleTitle: 'Função', termsText: 'Ao entrar, você concorda com os Termos de Serviço e Política de Privacidade do SiteFlow.', signOut: 'Sair', email: 'E-mail', password: 'Senha', accessDenied: 'Acesso Negado', pendingApproval: 'Aprovação Pendente', contactAdmin: 'Por favor, contate o seu administrador.', },
  roles: { manager: 'Gerente', cra: 'CRA', lead: 'Líder', super_admin: 'Super Administrador', },
  status: { active: 'Ativo', pending: 'Pendente', rejected: 'Rejeitado', },
  dashboard: { overview: 'Visão geral das atividades.', todayLogs: 'Hoje', thisWeekLogs: 'Esta Semana', openQueries: 'Consultas Abertas', actions: 'Ações', logNewActivity: 'Registrar Nova Atividade', viewHistory: 'Ver Histórico', quickLog: 'REGISTRO RÁPIDO', repeatRecent: 'Repetir Reciente', activityDistribution: 'Distribuição de Atividade', recentEntries: 'Entradas Recientes', viewAll: 'Ver Tudo', noRecentEntries: 'Nenhuma entrada recente.', time: 'Tempo', entries: 'Entradas', },
  shell: { appName: 'SiteFlow', appSubtitle: 'Registro de Operações Clínicas', smartTimer: 'Timer Inteligente', stopLog: 'Parar e Registrar', notifications: 'Notificações', markAllRead: 'Marcar todas como lidas', clearAll: 'Limpar todas', noNotifications: 'Nenhuma notificação nova', },
  logForm: { title: 'Registrar Tempo', subtitle: 'Registrar atividades como', aiSmartLogging: 'Registro Inteligente IA', aiDescription: 'Descreva o que você fez naturalmente, e nossa IA preencherá o formulário para você.', aiPlaceholder: 'ex., Passei 2 horas revisando Termos de Consentimento para o Protocolo A no Local 101...', aiButton: 'Preenchimento Automático', date: 'Data', duration: 'Duração', project: 'Projeto', protocol: 'Protocolo', siteOptional: 'Local (Opcional)', category: 'Categoria', specificActivity: 'Atividade Específica', task: 'Tarefa', notesOptional: 'Notas (Opcional)', notesPlaceholder: 'Adicione qualquer contexto ou detalhe adicional...', submit: 'Salvar Registro', selectProject: 'Selecionar Projeto...', selectProtocol: 'Selecionar Protocolo...', selectSite: 'Selecionar Local...', hours: 'h', minutes: 'm', aiSuccess: 'A IA preencheu o formulário com sucesso.', aiError: 'Falha ao processar o texto. Por favor, preencha manualmente.', },
  history: { title: 'Histórico e Consultas', subtitle: 'Revise registros e responda a consultas de dados.', searchPlaceholder: 'Buscar por categoria ou atividade...', allProjects: 'Todos os Projetos', allProtocols: 'Todos os Protocolos', date: 'Data', duration: 'Duração', project: 'Projeto', category: 'Categoria', activity: 'Atividade', noLogs: 'Nenhum registro encontrado com os filtros atuais.', openQuery: 'Abrir Consulta', askQuestion: 'Fazer Pergunta', question: 'Pergunta', reply: 'Responder', yourReply: 'Sua Resposta', sendReply: 'Enviar Resposta', },
  reports: { title: 'Relatórios e Análises', subtitle: 'Visualize a distribuição de tempo e estatísticas.', timeByProject: 'Tempo por Projeto', timeByCategory: 'Tempo por Categoria', noData: 'Nenhum dado disponível para exibir relatórios.', export: 'Exportar CSV', },
  team: { title: 'Gestão de Equipe', subtitle: 'Gerencie acessos e atribuições da equipe.', users: 'Usuários', projects: 'Projetos', protocols: 'Protocolos', name: 'Nome', role: 'Função', status: 'Status', actions: 'Ações', approve: 'Aprovar', reject: 'Rejeitar', },
};

export const dictionaries: Record<Language, Dictionary> = { en, es, pt };
